t0 = 1900
pcrum0 = interpolate(t0, pcrumt, pcrumts) * 1e-2
pop0 = interpolate(t0, popt, popts) * 1e8
ppgio0 = pcrum0 * pop0 * default_parameters["frpmv"] * default_parameters["imefv"] * default_parameters["imtiv"]
aiph0 = interpolate(t0, aipht, aiphts)
al0 = interpolate(t0, alt, alts) * 1e8
ppgao0 = aiph0 * al0 * default_parameters["fipmv"] * default_parameters["amtiv"]
ppgr0 = (ppgio0 + ppgao0) * default_parameters["ppgf1v"]
pptd0 = clip(default_parameters["pptd2v"], default_parameters["pptd1v"], t0, default_parameters["pyearv"])
ppapr30 = pptd0 * ppgr0 / 3
ppol0 = 2.5e7
pcti0 = 1
ppgf220 = pcti0
ppolx0 = ppol0 / default_parameters["ppol70v"]
lmp10 = interpolate(ppolx0, lmp1t, lmp1ts)
lmp20 = interpolate(ppolx0, lmp2t, lmp2ts)
lmp0 = clip(lmp20, lmp10, t0, default_parameters["pyearv"])
plmp0 = lmp0
