using WorldDynamics, Test, PlotlyJS

@testset verbose=true "World3" begin

    @testset "Agriculture" begin
        @test isa(World3.Agriculture.fig_69a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_69b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_69c(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_69d(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_70a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_70b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_70c(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_70d(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_72a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_72b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_73a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_73b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_74a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_74b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_75a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_75b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_76a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_76b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_77a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_77b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_78a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_78b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_82a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_82b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_83a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_83b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_84a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_84b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_85a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_85b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_86a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_86b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_87a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_87b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_88a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_88b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_89a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_89b(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_90a(), PlotlyJS.SyncPlot)
        @test isa(World3.Agriculture.fig_90b(), PlotlyJS.SyncPlot)
    end

    @testset "Capital" begin
        @test isa(World3.Capital.fig_36(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_37(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_38(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_39(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_40(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_41(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_42(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_43(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_44(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_45(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_46(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_47(), PlotlyJS.SyncPlot)
        @test isa(World3.Capital.fig_48(), PlotlyJS.SyncPlot)
    end

    @testset "Pollution" begin
        @test isa(World3.Pollution.fig_28(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_29(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_30(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_31(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_32(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_33(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_34(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_35(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_36(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_37(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_38(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_39(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_40(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_41(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_43(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_44(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_45(), PlotlyJS.SyncPlot)
        @test isa(World3.Pollution.fig_46(), PlotlyJS.SyncPlot)
    end

    @testset "NonRenewable" begin
        @test isa(World3.NonRenewable.fig_25(), PlotlyJS.SyncPlot)
        @test isa(World3.NonRenewable.fig_26(), PlotlyJS.SyncPlot)
        @test isa(World3.NonRenewable.fig_28(), PlotlyJS.SyncPlot)
        @test isa(World3.NonRenewable.fig_29(), PlotlyJS.SyncPlot)
        @test isa(World3.NonRenewable.fig_30(), PlotlyJS.SyncPlot)
    end

    @testset "Pop1" begin
        @test isa(World3.Pop1.fig_84(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_85(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_86(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_87(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_88(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_89(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_90(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_91(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_93(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_96(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_97(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_98(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_99(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_100(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_103a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_103b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop1.fig_103c(), PlotlyJS.SyncPlot)
    end

    @testset "Pop4" begin
        @test isa(World3.Pop4.fig_84(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_85(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_86(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_87(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_88(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_89(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_90(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_91(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_93(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_96(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_97(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_98(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_99(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_100(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_101a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_101b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_101c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_102a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_102b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_102c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_104a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_104b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_104c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_105a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_105b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_105c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_106a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_106b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_106c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_107a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_107b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_107c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_108a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_108b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_108c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_109a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_109b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_109c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_110a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_110b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_110c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_111a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_111b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_111c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_112a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_112b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_112c(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_113a(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_113b(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop4.fig_113c(), PlotlyJS.SyncPlot)
    end

    @testset "Pop15" begin
        @test isa(World3.Pop15.fig_84(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_85(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_86(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_87(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_88(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_89(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_90(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_91(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_93(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_96(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_97(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_98(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_99(), PlotlyJS.SyncPlot)
        @test isa(World3.Pop15.fig_100(), PlotlyJS.SyncPlot)
    end

    @testset "World3" begin
        @test isa(World3.fig_10(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_11(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_13(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_14(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_15(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_16(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_18(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_19(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_20(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_21(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_22(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_34(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_35(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_36(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_37(), PlotlyJS.SyncPlot)
        @test isa(World3.fig_38(), PlotlyJS.SyncPlot)
    end

end
